name: Run Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT for OIDC
  contents: read # This is required for actions/checkout

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "./go.mod"
        id: go

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false

      - name: Setup atmos
        uses: cloudposse/github-action-setup-atmos@60878d48037763f759aedee74e9cc0c2dc88e9ec # v3.5.0
        with:
          install-wrapper: false
          # TODO: Remove this once the issue is fixed https://github.com/cloudposse/atmos/issues/1064
          atmos-version: 1.161.0

      - name: Get dependencies
        run: go mod download

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: arn:aws:iam::799847381734:role/cptest-test-gbl-sandbox-tester
          role-session-name: githubaction-test-repo-test-helpers
          aws-region: us-east-2

      - name: Run tests
        run: |
          go test ./...
